[build]
  command = "pnpm i --frozen-lockfile && pnpm build:client"
  publish = "dist/spa"

[[redirects]]
  from = "/api/*"
  to = "https://studio-h47t.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
